name: Control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pytest flake8

      - name: Run tests
        run: pytest

      - name: Run flake8
        run: flake8 .
        uses: py-actions/flake8@v2